[package]
name = "hcp2-hp-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
hcp2-common = { path = "../common" }
panic-halt = "0.2.0"

[profile.release]
panic = "abort"
